### ISSUE TITLE
transmissions.find is deprecated?

### ISSUE THREAD

**Issue by Tallyb** [SparkPost/node-sparkpost#178]
when  posting the following: 
https://api.sparkpost.com/api/v1/transmissions/<id>

The following message returns: {
  "errors": [
    {
      "message": "You may use the Message Events API to retrieve event data for your transmission. For example https://api.sparkpost.com/api/v1/message-events?from=2016-09-20T09:00&transmission_ids=<id>"
    }
  ]
}
seems like the find method is deprecated by sparkpost

**Comment by aydrian** [comment]
Hi. It's not deprecated. That's just a helpful message that you can find more information about a transmission using our message events api. This method is mainly used for finding scheduled transmissions.

**Comment by Tallyb** [comment]
I could see the message event for a specific transmission but could not get it in the 
`https://api.sparkpost.com/api/v1/transmissions/<id>` API. Keep getting the error. 
Also in the documentation for transmissions you only have post and delete APIs. 
I think it will be adequate to remove the find from the list of options.

**Comment by aydrian** [comment]
In the documentation, we have retrieve which is the `GET` request. https://developers.sparkpost.com/api/transmissions.html#transmissions-retrieve-and-delete-get. This method is still valid. However, it will be changing to a `get()` method for version 2.0.
If the transmission you are trying to retrieve isn't a scheduled one, then you most likely won't see anything for it. Once a transmission is sent, you're best using the message-events api to get info on it.

I'm going to go ahead and close this because everything is in working order. Feel free to chat with us on our [community slack](http://slack.sparkpost.com).
