### ISSUE TITLE
Implement promises with callback support.

### ISSUE THREAD

**Issue by aydrian** [SparkPost/node-sparkpost#28]
Use this pull request as a guide.
https://github.com/SparkPost/node-sparkpost/pull/24

**Comment by jasonrhodes** [comment]
I went back and forth a lot on this, testing out different solutions, and I think the best method is to show how to convert our API to promises using your favorite promise library's `denodeify` method, rather than trying to handle the promise conversion internally by hand. It's less convenient for users but it's also less bug-prone as well as allowing users to choose their own promise library rather than shipping our SDK with `q`.

**Comment by max-mathieu** [comment]
Instead of trying to have functions that support both based on the presence of a callback, I saw some libs where you can do things like
var sparkpost = require('sparkpost').promises
and that promises object exposes all functions of the "regular" object.

Thoughts?

**Comment by jasonrhodes** [comment]
@max-mathieu I considered that, but it ships `q` and requires us to maintain the duplicate promises object whenever we add/remove from the callback API, which seemed like more overhead than it was worth.
